### ISSUE TITLE
opening / saving quarto .qmd files issue

### ISSUE THREAD

**Issue by teuffy** [hrbrmstr/rstudio-electron-quarto-installer#2]
- When opening / saving .qmd file, the blank screen with menu appears and a reset(**) is needed on macos apple silicon. testing on 2022.06.0-daily 217/218/208.
- The issue (quarto file) is not present with 2022.02.1 (intel/rosetta version)
-  (**) Reset on macos:
    https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State
    or
   mv ~/.local/share/rstudio ~/.local/share/rstudio-backup

**Comment by hrbrmstr** [comment]
Thank you!

I'm adding a check for the architecture being arm64 and the presence of open `qmd` files. If that combo is found it'll prompt folks to come to this issue's URL.

**Comment by hrbrmstr** [comment]
It'll print:

```
Checking if it's OK to install the Electron version of RStudio…

OPEN QMD FILES DETECTED.

RStudio Electron (on Apple Silicon) presently has issues with QMD files.

Please see:
  <https://github.com/hrbrmstr/rstudio-electron-quarto-installer/issues/2>
on how to reset your RStudio desktop state.
```

now (as soon as push the commit.
