### ISSUE TITLE
Rstudio daily json url change?

### ISSUE THREAD

**Issue by emitanaka** [hrbrmstr/rstudio-electron-quarto-installer#3]
It looks like `https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/macos/index.json` is no longer showing anything? (It just shows a blank page for me). I'm switching to using these url instead: `https://dailies.rstudio.com/rstudio/latest/index.json` or `https://dailies.rstudio.com/rstudio/spotted-wakerobin/index.json` .

**Comment by ghost** [comment]
ah! thank you! I'll get it updated. it was failing for me as well but i've been DoS'd @ work.

**Comment by hrbrmstr** [comment]
Fixed in today's push! #ty again!

**Comment by emitanaka** [comment]
Thanks for fixing it so quick!
